import {
  about,
  blog,
  changelog,
  contact,
  feature,
  integration,
  pages,
  pricing,
  service,
  industry,
} from "./types/pages.collections";
import {
  aboutBannerSection,
  changelogSection,
  ctaCareerSection,
  ctaSection1,
  ctaSection2,
  customersLogoSection,
  featuresCardLayoutSection,
  featuresGridSection,
  featuresSections,
  homeBannerSection,
  integrationSection,
  ourTeamSection,
  pricingCompareSection,
  pricingSection,
  testimonialSection,
  valuesSection,
} from "./types/sections.collections";

// Export collections
export const collections = {
  // Pages
  about,
  blog,
  changelog,
  contact,
  feature,
  integration,
  pages,
  pricing,
  service,
  industry,

  // Sections
  aboutBannerSection,
  ctaSection1,
  ctaSection2,
  ctaCareerSection,
  changelogSection,
  customersLogoSection,
  featuresCardLayoutSection,
  featuresGridSection,
  featuresSections,
  homeBannerSection,
  integrationSection,
  ourTeamSection,
  pricingCompareSection,
  pricingSection,
  testimonialSection,
  valuesSection,
};
